default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DB_HOST', '') %>
  password: <%= ENV.fetch('DB_PASS', '') %>
  username: <%= ENV.fetch('DB_USER', '') %>
development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'mystery_lunch_development') %>
test:
  <<: *default
  database: mystery_lunch_test

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'mystery_lunch') %>
