default: &default
  defautl_password: <%= ENV["DEFAUTL_PASSWORD"] || "cool_password" %>
  number_of_employees: <%= ENV["NUMBER_OF_EMPLOYEES"] || 4 %>
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
